defaults:
  - _self_

early_stopping:
  patience: 10
  delta: 0.0

# Main configuration attributes
seed: 0
lr: 0.0005
epochs: 100
seqs: 60
alpha: 0.05
T: 0
batch_size: 50
save_dir: models
save: true
l1_lambda: 0.0
l2_lambda: 0.0
net_batch_size: 50